{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ratelimit.name" . }}-redis
  labels:
    app: {{ include "ratelimit.name" . }}-redis
spec:
  ports:
    - name: redis
      port: 6379
  selector:
    app: {{ include "ratelimit.name" . }}-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ratelimit.name" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ratelimit.name" . }}-redis
  template:
    metadata:
      labels:
        app: {{ include "ratelimit.name" . }}-redis
    spec:
      containers:
        - image: redis:alpine
          imagePullPolicy: IfNotPresent
          name: redis
          ports:
            - name: redis
              containerPort: 6379
          resources:
{{ toYaml .Values.redis.resources | indent 12 }}
{{- end }}
