apiVersion: v1
kind: Service
metadata:
  name: {{ include "ratelimit.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "ratelimit.name" . }}
spec:
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc-port
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: http-debug
      port: 6070
      targetPort: 6070
      protocol: TCP
  selector:
    app: {{ include "ratelimit.name" . }}
